//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReader.v4UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODataReader.v4UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Action Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Action_element {
            get {
                return ResourceManager.GetString("Action_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ActionImport Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string ActionImport_element {
            get {
                return ResourceManager.GetString("ActionImport_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Annotation Term=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;.
        /// </summary>
        internal static string Annotation_element {
            get {
                return ResourceManager.GetString("Annotation_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Collection xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;.
        /// </summary>
        internal static string Collection_element {
            get {
                return ResourceManager.GetString("Collection_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ComplexType Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string ComplexType_element {
            get {
                return ResourceManager.GetString("ComplexType_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;edmx:DataServices xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot; /&gt;
        ///.
        /// </summary>
        internal static string DataServices_element {
            get {
                return ResourceManager.GetString("DataServices_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;4.0&quot; xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot; /&gt;
        ///.
        /// </summary>
        internal static string Edmx_element {
            get {
                return ResourceManager.GetString("Edmx_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EntityContainer Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string EntityContainer_element {
            get {
                return ResourceManager.GetString("EntityContainer_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EntitySet Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string EntitySet_element {
            get {
                return ResourceManager.GetString("EntitySet_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EntityType Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string EntityType_element {
            get {
                return ResourceManager.GetString("EntityType_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EnumType Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string EnumType_element {
            get {
                return ResourceManager.GetString("EnumType_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Function Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Function_element {
            get {
                return ResourceManager.GetString("Function_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FunctionImport Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string FunctionImport_element {
            get {
                return ResourceManager.GetString("FunctionImport_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Key xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Key_element {
            get {
                return ResourceManager.GetString("Key_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Member Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Member_element {
            get {
                return ResourceManager.GetString("Member_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NavigationProperty Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string NavigationProperty_element {
            get {
                return ResourceManager.GetString("NavigationProperty_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NavigationPropertyPath xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;.
        /// </summary>
        internal static string NavigationPropertyPath_element {
            get {
                return ResourceManager.GetString("NavigationPropertyPath_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;4.0&quot; xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot;&gt;
        ///  &lt;edmx:DataServices&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.OneNote.Api&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot;&gt;
        ///      &lt;EntityType Name=&quot;Notebook&quot;&gt;
        ///        &lt;Key&gt;
        ///          &lt;PropertyRef Name=&quot;id&quot; /&gt;
        ///        &lt;/Key&gt;
        ///        &lt;Property Name=&quot;isDefault&quot; Type=&quot;Edm.Boolean&quot; /&gt;
        ///        &lt;Property Name=&quot;userRole&quot; Type=&quot;Microsoft.OneNote.Api.UserRole&quot; /&gt;
        ///        &lt;Property Name=&quot;isShared&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneNoteExampleEdmx {
            get {
                return ResourceManager.GetString("OneNoteExampleEdmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Parameter Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Parameter_element {
            get {
                return ResourceManager.GetString("Parameter_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Property Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Property_element {
            get {
                return ResourceManager.GetString("Property_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PropertyPath xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;.
        /// </summary>
        internal static string PropertyPath_element {
            get {
                return ResourceManager.GetString("PropertyPath_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PropertyRef xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;.
        /// </summary>
        internal static string PropertyRef_element {
            get {
                return ResourceManager.GetString("PropertyRef_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PropertyValue Property=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string PropertyValue_element {
            get {
                return ResourceManager.GetString("PropertyValue_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Record xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Record_element {
            get {
                return ResourceManager.GetString("Record_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ReturnType xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string ReturnType_element {
            get {
                return ResourceManager.GetString("ReturnType_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema Namespace=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Schema_element {
            get {
                return ResourceManager.GetString("Schema_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Singleton Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Singleton_element {
            get {
                return ResourceManager.GetString("Singleton_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;4.0&quot; xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot;&gt;
        ///  &lt;edmx:DataServices&gt;
        ///    &lt;Schema Namespace=&quot;namespace&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot;&gt;
        ///      &lt;EnumType Name=&quot;name&quot; UnderlyingType=&quot;namespace.name&quot; IsFlags=&quot;true&quot;&gt;
        ///        &lt;Member Name=&quot;name&quot; Value=&quot;0&quot;/&gt;
        ///      &lt;/EnumType&gt;
        ///      &lt;ComplexType Name=&quot;name&quot; BaseType=&quot;namespace.name&quot; Abstract=&quot;true&quot; OpenType=&quot;true&quot;&gt;
        ///        &lt;Property Name=&quot;name&quot; Type=&quot;namespace.name&quot; Null [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_edmx {
            get {
                return ResourceManager.GetString("template_edmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TypeDefinition Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string TypeDefintionType_element {
            get {
                return ResourceManager.GetString("TypeDefintionType_element", resourceCulture);
            }
        }
    }
}
