//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ODataReader.v3UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ODataReader.v3UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Association Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Association_element {
            get {
                return ResourceManager.GetString("Association_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;AssociationSet Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string AssociationSet_element {
            get {
                return ResourceManager.GetString("AssociationSet_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ComplexType Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string ComplexType_element {
            get {
                return ResourceManager.GetString("ComplexType_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;edmx:DataServices DataServicesVersion=&quot;3.0&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; /&gt;
        ///.
        /// </summary>
        internal static string DataServices_element {
            get {
                return ResourceManager.GetString("DataServices_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;1.0&quot; xmlns:edmx=&quot;http://schemas.microsoft.com/ado/2007/06/edmx&quot; /&gt;
        ///.
        /// </summary>
        internal static string Edmx_element {
            get {
                return ResourceManager.GetString("Edmx_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;End xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string End_element {
            get {
                return ResourceManager.GetString("End_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EntityContainer Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string EntityContainer_element {
            get {
                return ResourceManager.GetString("EntityContainer_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EntitySet Name=&quot;{0}&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string EntitySet_element {
            get {
                return ResourceManager.GetString("EntitySet_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EntityType Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string EntityType_element {
            get {
                return ResourceManager.GetString("EntityType_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EnumType Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string EnumType_element {
            get {
                return ResourceManager.GetString("EnumType_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FunctionImport Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string FunctionImport_element {
            get {
                return ResourceManager.GetString("FunctionImport_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Key xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Key_element {
            get {
                return ResourceManager.GetString("Key_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Member Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Member_element {
            get {
                return ResourceManager.GetString("Member_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NavigationProperty Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string NavigationProperty_element {
            get {
                return ResourceManager.GetString("NavigationProperty_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Parameter Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Parameter_element {
            get {
                return ResourceManager.GetString("Parameter_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Property Name=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Property_element {
            get {
                return ResourceManager.GetString("Property_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PropertyRef xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;.
        /// </summary>
        internal static string PropertyRef_element {
            get {
                return ResourceManager.GetString("PropertyRef_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Schema Namespace=&quot;{0}&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot; /&gt;
        ///.
        /// </summary>
        internal static string Schema_element {
            get {
                return ResourceManager.GetString("Schema_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;1.0&quot; xmlns:edmx=&quot;http://schemas.microsoft.com/ado/2007/06/edmx&quot;&gt;
        ///  &lt;edmx:DataServices DataServicesVersion=&quot;3.0&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;
        ///    &lt;Schema Namespace=&quot;namespace&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot;&gt;
        ///      &lt;EnumType Name=&quot;name&quot; UnderlyingType=&quot;namespace.name&quot; IsFlags=&quot;true&quot;&gt;
        ///        &lt;Member Name=&quot;name&quot; Value=&quot;0&quot;/&gt;
        ///      &lt;/EnumType&gt;
        ///      &lt;ComplexType Name=&quot;name&quot; BaseTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_edmx {
            get {
                return ResourceManager.GetString("template_edmx", resourceCulture);
            }
        }
    }
}
