//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpWriterUnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpWriterUnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;1.0&quot; xmlns:edmx=&quot;http://schemas.microsoft.com/ado/2007/06/edmx&quot;&gt;
        ///  &lt;edmx:DataServices m:DataServiceVersion=&quot;3.0&quot; m:MaxDataServiceVersion=&quot;3.0&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.DirectoryServices&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot;&gt;
        ///      &lt;EntityType Name=&quot;DirectoryObject&quot; OpenType=&quot;true&quot;&gt;
        ///        &lt;Key&gt;
        ///          &lt;PropertyRef Name=&quot;objectId&quot; /&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActiveDirectory_ODataV3 {
            get {
                return ResourceManager.GetString("ActiveDirectory_ODataV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;1.0&quot; xmlns:edmx=&quot;http://schemas.microsoft.com/ado/2007/06/edmx&quot;&gt;
        ///  &lt;edmx:DataServices xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:DataServiceVersion=&quot;1.0&quot;&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.Crm.Sdk.Data.Services&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2007/05/edm&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CRM_ODataV1 {
            get {
                return ResourceManager.GetString("CRM_ODataV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;4.0&quot; xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot;&gt;
        ///  &lt;edmx:DataServices&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.OutlookServices&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot;&gt;
        ///      &lt;EnumType Name=&quot;DayOfWeek&quot;&gt;
        ///        &lt;Member Name=&quot;Sunday&quot; Value=&quot;0&quot; /&gt;
        ///        &lt;Member Name=&quot;Monday&quot; Value=&quot;1&quot; /&gt;
        ///        &lt;Member Name=&quot;Tuesday&quot; Value=&quot;2&quot; /&gt;
        ///        &lt;Member Name=&quot;Wednesday&quot; Value=&quot;3&quot; /&gt;
        ///        &lt;Member Name=&quot;Thursday&quot; Value=&quot;4&quot; /&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Exchange_ODataV4 {
            get {
                return ResourceManager.GetString("Exchange_ODataV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;edmx:Edmx Version=&quot;4.0&quot; xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot;&gt;
        ///  &lt;edmx:DataServices&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.OneNote.Api&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot;&gt;
        ///      &lt;EntityType Name=&quot;Notebook&quot;&gt;
        ///        &lt;Key&gt;
        ///          &lt;PropertyRef Name=&quot;id&quot; /&gt;
        ///        &lt;/Key&gt;
        ///        &lt;Property Name=&quot;isDefault&quot; Type=&quot;Edm.Boolean&quot; /&gt;
        ///        &lt;Property Name=&quot;userRole&quot; Type=&quot;Microsoft.OneNote.Api.UserRole&quot; /&gt;
        ///        &lt;Property Name=&quot;isShared&quot; Type=&quot;Edm.Boolean&quot; /&gt;
        ///        &lt;Property [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneNote_ODataV4 {
            get {
                return ResourceManager.GetString("OneNote_ODataV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;4.0&quot; xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot;&gt;
        ///  &lt;edmx:DataServices&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.CoreServices&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot;&gt;
        ///      &lt;!--&lt;EntityType Name=&quot;CurrentUserRequestContext&quot;&gt;
        ///        &lt;Key&gt;
        ///          &lt;PropertyRef Name=&quot;id&quot; /&gt;
        ///        &lt;/Key&gt;
        ///        &lt;Property Name=&quot;id&quot; Type=&quot;Edm.String&quot; Nullable=&quot;false&quot; /&gt;
        ///        &lt;NavigationProperty Name=&quot;drive&quot; Type=&quot;Microsoft.FileServices.Drive&quot; Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SharePoint_ODataV4 {
            get {
                return ResourceManager.GetString("SharePoint_ODataV4", resourceCulture);
            }
        }
    }
}
