//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vipr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vipr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;1.0&quot; xmlns:edmx=&quot;http://schemas.microsoft.com/ado/2007/06/edmx&quot;&gt;
        ///  &lt;edmx:DataServices m:DataServiceVersion=&quot;3.0&quot; m:MaxDataServiceVersion=&quot;3.0&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot;&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.DirectoryServices&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2009/11/edm&quot;&gt;
        ///      &lt;EntityType Name=&quot;DirectoryObject&quot; OpenType=&quot;true&quot;&gt;
        ///        &lt;Key&gt;
        ///          &lt;PropertyRef Name=&quot;objectId&quot; /&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aadgraph_edmx {
            get {
                return ResourceManager.GetString("aadgraph_edmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;1.0&quot; xmlns:edmx=&quot;http://schemas.microsoft.com/ado/2007/06/edmx&quot;&gt;
        ///  &lt;edmx:DataServices xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; m:DataServiceVersion=&quot;1.0&quot;&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.Crm.Sdk.Data.Services&quot; xmlns:d=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices&quot; xmlns:m=&quot;http://schemas.microsoft.com/ado/2007/08/dataservices/metadata&quot; xmlns=&quot;http://schemas.microsoft.com/ado/2007/05/edm&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dynamicsCrm_edmx {
            get {
                return ResourceManager.GetString("dynamicsCrm_edmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;4.0&quot; xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot;&gt;
        ///  &lt;edmx:DataServices&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.Exchange.Services.OData.Model&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot;&gt;
        ///      &lt;EnumType Name=&quot;BodyType&quot;&gt;
        ///        &lt;Member Name=&quot;Text&quot; Value=&quot;0&quot; /&gt;
        ///        &lt;Member Name=&quot;HTML&quot; Value=&quot;1&quot; /&gt;
        ///      &lt;/EnumType&gt;
        ///      &lt;EnumType Name=&quot;Importance&quot;&gt;
        ///        &lt;Member Name=&quot;Normal&quot; Value=&quot;0&quot; /&gt;
        ///        &lt;Member Name=&quot;Low&quot; Value=&quot;1&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exchange_edmx {
            get {
                return ResourceManager.GetString("exchange_edmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;edmx:Edmx xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot; Version=&quot;4.0&quot;&gt;
        ///    &lt;edmx:Reference Uri=&quot;http://docs.oasis-open.org/odata/odata/v4.0/cs01/vocabularies/Org.OData.Core.V1.xml&quot;&gt;
        ///        &lt;edmx:Include Namespace=&quot;Org.OData.Core.V1&quot; Alias=&quot;Core&quot; /&gt;
        ///    &lt;/edmx:Reference&gt;
        ///    &lt;edmx:Reference Uri=&quot;http://docs.oasis-open.org/odata/odata/v4.0/cs01/vocabularies/Org.OData.Measures.V1.xml&quot;&gt;
        ///        &lt;edmx:Include Alias=&quot;UoM&quot; Namespace=&quot;Org.OData.Measures.V1&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string odataDemo_edmx {
            get {
                return ResourceManager.GetString("odataDemo_edmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;edmx:Edmx Version=&quot;4.0&quot; xmlns:edmx=&quot;http://docs.oasis-open.org/odata/ns/edmx&quot;&gt;
        ///  &lt;edmx:DataServices&gt;
        ///    &lt;Schema Namespace=&quot;Microsoft.CoreServices&quot; xmlns=&quot;http://docs.oasis-open.org/odata/ns/edm&quot;&gt;
        ///      &lt;!--&lt;EntityType Name=&quot;CurrentUserRequestContext&quot;&gt;
        ///        &lt;Key&gt;
        ///          &lt;PropertyRef Name=&quot;id&quot; /&gt;
        ///        &lt;/Key&gt;
        ///        &lt;Property Name=&quot;id&quot; Type=&quot;Edm.String&quot; Nullable=&quot;false&quot; /&gt;
        ///        &lt;NavigationProperty Name=&quot;drive&quot; Type=&quot;Microsoft.FileServices.Drive&quot; Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sharepoint_full_edmx {
            get {
                return ResourceManager.GetString("sharepoint_full_edmx", resourceCulture);
            }
        }
    }
}
